# Регистрация пользователя

POST http://localhost:8081/auth/register
Content-Type: application/json

{
  "username": "leader",
  "password": "test",
  "firstName": "test",
  "middleName": "test",
  "lastName": "test",
  "role": "ROLE_LEADER"
}

###  Принятие заявки пользователя
POST http://localhost:8081/admin/register/approve/6

###  Отклонение заявки пользователя
POST http://localhost:8081/admin/register/decline/3

###  Список ведущих
GET http://localhost:8081/admin/leaders

###  Список заявок на ведущих
GET http://localhost:8081/admin/waiting