---
logging:
  level:
    org.springframework.web: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      format_sql: true
      dialect:
    database: postgresql
  sql:
    init:
      platform: postgres
  flyway:
    locations: classpath:db/migration
server:
  port : 8081
  address: 127.0.0.1
